# Generated by Django 5.0 on 2023-12-31 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=1000)),
                ('short_code', models.CharField(max_length=50)),
                ('total_click', models.IntegerField(default=0)),
                ('order_type', models.CharField(choices=[('Next', 'Next'), ('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Solar', 'Solar'), ('Random', 'Random')], default='Next', max_length=50)),
                ('redirect_url_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BaseURL',
                'verbose_name_plural': 'BaseURLs',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Premium', 'Premium')], default='Normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='RedirectURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_url', models.CharField(max_length=1000)),
                ('total_redirect', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_url', to='api.baseurl')),
            ],
            options={
                'verbose_name': 'RedirectURL',
                'verbose_name_plural': 'RedirectURLS',
            },
        ),
    ]
