# Generated by Django 4.2 on 2023-12-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuttc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirects',
            options={'managed': True, 'verbose_name': 'Redirect URL', 'verbose_name_plural': 'Redirect URLS'},
        ),
        migrations.AlterModelOptions(
            name='urls',
            options={'managed': True, 'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
        migrations.AlterModelTable(
            name='redirects',
            table='Redirect_Urls',
        ),
        migrations.AlterModelTable(
            name='urls',
            table='URLs',
        ),
    ]
